apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-claim0
  labels:
    io.kompose.service: mysql-db-claim0
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"